use std::collections::BTreeMap;
use std::sync::Arc;

use vulkano::{
	instance::{Instance, InstanceCreateFlags, InstanceCreateInfo},
	device::{
		Device, DeviceCreateInfo, DeviceExtensions, Queue, QueueCreateInfo, QueueFlags,
		physical::{PhysicalDevice, PhysicalDeviceType},
	},
	command_buffer::{
		allocator::StandardCommandBufferAllocator,
		AutoCommandBufferBuilder, CommandBufferUsage, CopyImageInfo, CommandBufferExecFuture,
	},
	descriptor_set::{
		layout::{DescriptorSetLayoutBinding, DescriptorSetLayoutCreateInfo, DescriptorType},
		allocator::StandardDescriptorSetAllocator, DescriptorSet, WriteDescriptorSet,
	},
	format::{Format, FormatFeatures},
	image::{view::ImageView, Image, ImageCreateInfo, ImageTiling, ImageUsage},
	memory::allocator::{AllocationCreateInfo, StandardMemoryAllocator},
	pipeline::{
		layout::{PipelineDescriptorSetLayoutCreateInfo, PipelineLayoutCreateFlags},
		Pipeline, PipelineLayout, PipelineShaderStageCreateInfo, ComputePipeline,
		compute::ComputePipelineCreateInfo,
	},
	swapchain::{self, Surface, Swapchain, SwapchainCreateInfo, SwapchainPresentInfo, SwapchainAcquireFuture, PresentFuture},
	sync::{GpuFuture, future::{FenceSignalFuture, JoinFuture}},
	Validated, VulkanError,
};

use winit::event_loop::ActiveEventLoop;
use winit::window::Window;


pub struct Renderer {
	windows: Arc<Window>,
	device: Arc<Device>,
	queue: Arc<Queue>,
	swapchain: Arc<Swapchain>,
	swapchain_images: Vec<Arc<Image>>,
	memory_allocator: Arc<StandardMemoryAllocator>,
	cs_images: Vec<Arc<Image>>,
	command_buffer_allocator: Arc<StandardCommandBufferAllocator>,
	compute_pipeline: Arc<ComputePipeline>,
	descriptor_set_allocator: Arc<StandardDescriptorSetAllocator>,
	descriptor_sets: Vec<Arc<DescriptorSet>>,
	// This horrendous type is generated by chaining futures together
    fences: Vec<Option<Arc<
		// This bit is the type of the future returned by then_signal_fence_and_flush (unwrapped) when presenting
		FenceSignalFuture<PresentFuture<CommandBufferExecFuture<JoinFuture<Box<dyn GpuFuture>, SwapchainAcquireFuture>>>>
	>>>,
    previous_fence_i: usize,

	pub recreate_swapchain: bool,
}

impl Renderer {
	pub fn new(event_loop: &ActiveEventLoop, window: &Arc<Window>) -> Self {
		let library = vulkano::VulkanLibrary::new().expect("no local Vulkan library/DLL");

		let required_extensions = Surface::required_extensions(&event_loop).unwrap();
		let instance = Instance::new(
			library,
			InstanceCreateInfo {
				flags: InstanceCreateFlags::ENUMERATE_PORTABILITY,
				enabled_extensions: required_extensions,
				..Default::default()
			},
		)
		.expect("failed to create instance");

		let surface = Surface::from_window(instance.clone(), window.clone()).unwrap();

		let device_extensions = DeviceExtensions {
			khr_swapchain: true,
			..DeviceExtensions::empty()
		};

		let (physical_device, queue_family_index) = select_physical_device(&instance, &surface, &device_extensions);
		println!(
			"Using device: {} (type: {:?})",
			physical_device.properties().device_name,
			physical_device.properties().device_type
		);

		let (device, mut queues) = Device::new(
			physical_device.clone(),
			DeviceCreateInfo {
				queue_create_infos: vec![QueueCreateInfo {
					queue_family_index,
					..Default::default()
				}],
				enabled_extensions: device_extensions,
				..Default::default()
			},
		)
		.expect("failed to create device");

		let queue = queues.next().unwrap();

		let (swapchain, swapchain_images) = {
			let caps = physical_device
				.surface_capabilities(&surface, Default::default())
				.expect("failed to get surface capabilities");

			let dimensions = window.inner_size();
			let composite_alpha = caps.supported_composite_alpha.into_iter().next().unwrap();

			// Find a format that supports storage images and supported by the surface
			let image_format = physical_device
				.surface_formats(&surface, Default::default())
				.unwrap()
				.iter().find(|(format, color)| {
					(physical_device.format_properties(*format).unwrap()
						.format_features(ImageTiling::Optimal, Default::default())
						& FormatFeatures::TRANSFER_DST != FormatFeatures::empty())
					&& *color == vulkano::swapchain::ColorSpace::SrgbNonLinear
				}
				)
				.map(|(format, _)| *format)
				.expect("no supported format found");

			Swapchain::new(
				device.clone(),
				surface,
				SwapchainCreateInfo {
					min_image_count: caps.min_image_count,
					image_format,
					image_extent: dimensions.into(),
					image_usage: ImageUsage::TRANSFER_DST,
					composite_alpha,
					..Default::default()
				},
			)
			.unwrap()
		};
		let frames_in_flight = swapchain_images.len();

		// Allocate memory for compute shader images
		let memory_allocator = Arc::new(StandardMemoryAllocator::new_default(device.clone()));
		
		let (cs_images, cs_image_views) =
			create_compute_images(&memory_allocator, &swapchain_images);

		// Load compute shader
		const SHADER: &[u8] = include_bytes!(env!("<shader_crate>.spv"));
		mod cs {
			vulkano_shaders::shader! {
				ty: "compute",
				src: r"
					#version 460

					layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

					layout(set = 0, binding = 0, rgba8) uniform writeonly image2D img;

					void main() {
						vec2 norm_coordinates = (gl_GlobalInvocationID.xy + vec2(0.5)) / vec2(imageSize(img));

						vec2 c = (norm_coordinates - vec2(0.5)) * 2.0 - vec2(1.0, 0.0);

						vec2 z = vec2(0.0, 0.0);
						float i;
						for (i = 0.0; i < 1.0; i += 0.005) {
							z = vec2(
								z.x * z.x - z.y * z.y + c.x,
								z.y * z.x + z.x * z.y + c.y
							);

							if (length(z) > 4.0) {
								break;
							}
						}

						vec4 to_write = vec4(vec3(i), 1.0);
						imageStore(img, ivec2(gl_GlobalInvocationID.xy), to_write);
					}
				",
			}
		}

		let shader = cs::load(device.clone()).expect("failed to create shader module");

		let cs = shader.entry_point("main").unwrap();
		let stage = PipelineShaderStageCreateInfo::new(cs);
		let layout = PipelineLayout::new(
			device.clone(),
			PipelineDescriptorSetLayoutCreateInfo {
				flags: PipelineLayoutCreateFlags::empty(),
				set_layouts: vec![DescriptorSetLayoutCreateInfo {
					bindings: BTreeMap::from([(
						0,
						DescriptorSetLayoutBinding {
							stages: vulkano::shader::ShaderStages::COMPUTE,
							descriptor_type: DescriptorType::StorageImage,
							descriptor_count: 1,
							..DescriptorSetLayoutBinding::descriptor_type(DescriptorType::StorageImage)
						},
					)]),
					..Default::default()
				}],
				push_constant_ranges: vec![],
			}
				.into_pipeline_layout_create_info(device.clone())
				.unwrap(),
		)
		.unwrap();

		let compute_pipeline = ComputePipeline::new(
			device.clone(),
			None,
			ComputePipelineCreateInfo::stage_layout(stage, layout),
		)
		.expect("failed to create compute pipeline");

		// Create descriptor sets
		let descriptor_set_allocator = Arc::new(StandardDescriptorSetAllocator::new(device.clone(), Default::default()));

		let descriptor_sets = create_compute_image_descriptor_sets(
			&descriptor_set_allocator,
			compute_pipeline.layout().set_layouts().get(0).unwrap(),
			&cs_image_views,
		);

		// Create command buffer allocator
		let command_buffer_allocator = Arc::new(StandardCommandBufferAllocator::new(device.clone(), Default::default()));

		Self {
			windows: window.clone(),
			device,
			queue,
			swapchain,
			swapchain_images,
			memory_allocator,
			cs_images,
			command_buffer_allocator,
			compute_pipeline,
			descriptor_set_allocator,
			descriptor_sets,
			fences: vec![None; frames_in_flight],
			previous_fence_i: 0,
			recreate_swapchain: false,
		}
	}

	pub fn draw(&mut self) {
		if self.recreate_swapchain {
			self.recreate_swapchain();
		}
		// Get the next image from the swapchain
		let (image_i, suboptimal, acquire_swapchain_image_future) =
			match swapchain::acquire_next_image(self.swapchain.clone(), None)
				.map_err(Validated::unwrap)
			{
				Ok(r) => (r.0 as usize, r.1, r.2),
				Err(VulkanError::OutOfDate) => {
					self.recreate_swapchain = true;
					return;
				}
				Err(e) => panic!("failed to acquire next image: {e}"),
			};
		
		if suboptimal {
			self.recreate_swapchain = true;
		}
		
		// wait for the fence related to this image to finish
		if let Some(image_fence) = &self.fences[image_i] {
			image_fence.wait(None).unwrap();
		}

		let previous_future = match self.fences[self.previous_fence_i].clone() {
			// Create a NowFuture
			None => {
				let mut now = vulkano::sync::now(self.device.clone());
				now.cleanup_finished();

				now.boxed()
			}
			// Use the existing FenceSignalFuture
			Some(fence) => fence.boxed(),
		};
		

		let mut cmd_buf_builder = AutoCommandBufferBuilder::primary(
			self.command_buffer_allocator.clone(),
			self.queue.queue_family_index(),
			CommandBufferUsage::OneTimeSubmit,
		)
		.unwrap();

		cmd_buf_builder.bind_pipeline_compute(self.compute_pipeline.clone()).unwrap();
		cmd_buf_builder.bind_descriptor_sets(
			vulkano::pipeline::PipelineBindPoint::Compute,
			self.compute_pipeline.layout().clone(),
			0,
			self.descriptor_sets[image_i].clone(),
		).unwrap();

		unsafe {
			cmd_buf_builder.dispatch(
				[self.swapchain.image_extent()[0] / 8, self.swapchain.image_extent()[1] / 8, 1]
			).unwrap();
		}

		cmd_buf_builder.copy_image(CopyImageInfo::images(
			self.cs_images[image_i].clone(),
			self.swapchain_images[image_i].clone()
		)).unwrap();

		let command_buffer = cmd_buf_builder.build().unwrap();

		let future = previous_future
			.join(acquire_swapchain_image_future)
			.then_execute(self.queue.clone(), command_buffer)
			.unwrap()
			.then_swapchain_present(
				self.queue.clone(),
				SwapchainPresentInfo::swapchain_image_index(self.swapchain.clone(), image_i as u32),
			)
			.then_signal_fence_and_flush();

		self.fences[image_i] = match future.map_err(Validated::unwrap) {
                Ok(value) => Some(Arc::new(value)),
                Err(VulkanError::OutOfDate) => {
                    self.recreate_swapchain = true;
                    None
                }
                Err(e) => {
                    println!("failed to flush future: {e}");
                    None
                }
            };

        self.previous_fence_i = image_i;
	}

	fn recreate_swapchain(&mut self) {
		// Recreate the swapchain
		let dimensions = self.windows.inner_size();

		(self.swapchain, self.swapchain_images) = self.swapchain.recreate(SwapchainCreateInfo {
			image_extent: dimensions.into(),
			..self.swapchain.create_info()
		})
		.expect("failed to recreate swapchain");

		let (new_cs_images, new_cs_image_views) =
			create_compute_images(&self.memory_allocator, &self.swapchain_images);
		self.cs_images = new_cs_images;
		
		self.descriptor_sets = create_compute_image_descriptor_sets(
			&self.descriptor_set_allocator,
			self.compute_pipeline.layout().set_layouts().get(0).unwrap(),
			&new_cs_image_views,
		);

		self.recreate_swapchain = false;
	}
}

fn select_physical_device(
    instance: &Arc<Instance>,
    surface: &Arc<Surface>,
    device_extensions: &DeviceExtensions,
) -> (Arc<PhysicalDevice>, u32) {
    instance
        .enumerate_physical_devices()
        .expect("failed to enumerate physical devices")
        .filter(|p| p.supported_extensions().contains(device_extensions))
        .filter_map(|p| {
            p.queue_family_properties()
                .iter()
                .enumerate()
                .position(|(i, q)| {
                    q.queue_flags.contains(QueueFlags::GRAPHICS)
                        && p.surface_support(i as u32, surface).unwrap_or(false)
                })
                .map(|q| (p, q as u32))
        })
        .min_by_key(|(p, _)| match p.properties().device_type {
            PhysicalDeviceType::DiscreteGpu => 0,
            PhysicalDeviceType::IntegratedGpu => 1,
            PhysicalDeviceType::VirtualGpu => 2,
            PhysicalDeviceType::Cpu => 3,
            _ => 4,
        })
        .expect("no device available")
}

fn create_compute_images(
	memory_allocator: &Arc<StandardMemoryAllocator>,
	swapchain_images: &Vec<Arc<Image>>,
) -> (Vec<Arc<Image>>, Vec<Arc<ImageView>>) {
	let cs_images: Vec<Arc<Image>> = swapchain_images
		.iter()
		.map(|image| {
			Image::new(
				memory_allocator.clone(),
				ImageCreateInfo {
					format: Format::R8G8B8A8_UNORM,
					extent: image.extent(),
					usage: ImageUsage::STORAGE | ImageUsage::TRANSFER_SRC,
					..Default::default()
				},
				AllocationCreateInfo::default(),
			)
			.unwrap()
		})
		.collect();

	let cs_image_views: Vec<Arc<ImageView>> = cs_images
		.iter()
		.map(|image| ImageView::new_default(image.clone()).unwrap())
		.collect();

	(cs_images, cs_image_views)
}

fn create_compute_image_descriptor_sets(
	descriptor_set_allocator: &Arc<StandardDescriptorSetAllocator>,
	layout: &Arc<vulkano::descriptor_set::layout::DescriptorSetLayout>,
	cs_image_views: &Vec<Arc<ImageView>>,
) -> Vec<Arc<DescriptorSet>> {
	let descriptor_sets = cs_image_views
		.iter()
		.map(|image_view| {
			DescriptorSet::new(
				descriptor_set_allocator.clone(),
				layout.clone(),
				[WriteDescriptorSet::image_view(0, image_view.clone())],
				[],
			)
			.unwrap()
		})
		.collect::<Vec<_>>();

	descriptor_sets
}
